#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["AutenticacaoAPI/AutenticacaoAPI.csproj", "AutenticacaoAPI/"]
COPY ["Infrastructure.Infra/Infrastructure.csproj", "Infrastructure.Infra/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["Service/Service.csproj", "Service/"]
RUN dotnet restore "./AutenticacaoAPI/AutenticacaoAPI.csproj"
COPY . .
WORKDIR "/src/AutenticacaoAPI"
RUN dotnet build "./AutenticacaoAPI.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./AutenticacaoAPI.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AutenticacaoAPI.dll"]