global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/prometheus_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq_exporter:9419']
  - job_name: 'postgres'
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres_exporter:9187']
  # - job_name: 'api'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['api:8080']
