{
 "title": "API Auth Server Management Dashboard",
 "tags": [
  "api",
  "auth"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": "label_values(http_requests_total, endpoint)"
   },
   {
    "name": "method",
    "label": "method",
    "query": "label_values(http_requests_total, method)"
   }
  ]
 },
 "panels": [
  {
   "title": "API Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (method, endpoint)"
    }
   ]
  },
  {
   "title": "API 95th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, method, endpoint)) * 1000"
    }
   ]
  },
  {
   "title": "API Average Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "((avg(rate(http_request_duration_seconds_sum[1m])) / avg(rate(http_request_duration_seconds_count[1m]))) * 1000)"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m])) by (endpoint)"
    }
   ]
  }
 ]
}