{
 "title": "PostgreSQL Monitoring Dashboard",
 "tags": [ "postgres" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "PostgreSQL Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "postgres_active_connections" }
   ]
  },
  {
   "title": "PostgreSQL Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "postgres_queries_per_second" }
   ]
  },
  {
   "title": "PostgreSQL Cache Hit Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "postgres_cache_hit_percentage" }
   ]
  },
  {
   "title": "PostgreSQL Commit Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "postgres_transactions_commit_rate"
    }
   ]
  },
  {
   "title": "PostgreSQL Rollback Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "postgres_transactions_rollback_rate"
    }
   ]
  },
  {
   "title": "PostgreSQL Deadlocks Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "postgres_deadlocks_rate" }
   ]
  }
 ]
}