name: CI

on:
  push:
    branches:
      - "feature/mesh"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  dockerhub:
    name: Push DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: 'yurisbk'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: 'yurisbk/techchallenge_imagem:latest'
          push: true

  build_and_test:
    name: Executa Testes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.204'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal

  push_to_main:
    name: Push to Main
    runs-on: ubuntu-latest
    needs: [dockerhub, build_and_test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Merge feature/mesh into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/feature/mesh --no-ff -m "Auto-merge feature/mesh into main"
          git push origin main
