name: CI

on:
  push:
    branches:
      - "feature/mesh"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  dockerhub:
    name: Executando primeiro job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: 'yurisbk'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: 'yurisbk/techchallenge_imagem:latest'
          push: true

  build_and_test:
    name: Executando segundo job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.204'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --filter Category=Unity --verbosity normal
